/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.automate.orangehrm;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        // System.setProperty("webdriver.gecko.driver",
        // );

        // WebDriver driver = new ChromeDriver();
        // driver.navigate().to("https://www.orangehrm.com/");
        System.out.println("Working");
    }
}
